language: bash

before_script:
	- git clone git@github.com:lede-project/source.git trunk_lede && cd trunk_lede
	- ./scripts/feeds update -a && ./scripts/feeds install -a
	- cp ../../configs_default/config_lede_trunk ./.config
	- cd tmp && git clone git@github.com:Sudokamikaze/PulshenWRT_LEDE.git
 	- cp -r PulshenWRT_LEDE/files ../build_dir/trunk_lede/
	- cd ../build_dir/trunk_lede && patch < ../../tmp/PulshenWRT_LEDE/PulshenWRT_LEDE.diff
	- cd target/linux/ar71xx/files/drivers/mtd/
	- patch < ../../../../../../../../tmp/PulshenWRT_LEDE/uboot_unlock.patch

script:
	- cd build_dir/trunk_lede
	- make tools/install ${MAKEFLAGS="-j$(nproc)"} V=-1 && make toolchain/install ${MAKEFLAGS="-j$(nproc)"} V=-1
	- make ${MAKEFLAGS="-j$(nproc)"} V=-1

